import { createServerSupabaseClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

async function authorized(supabase:any,communityId:string,userId:string){
 const {data:membership}=await supabase.from('community_memberships').select('is_owner').eq('community_id',communityId).eq('user_id',userId).eq('status','active').maybeSingle();
 if(membership?.is_owner)return true;
 const {data}=await supabase.rpc('has_permission',{target_community_id:communityId,requested_permission:'permissions.manage'}); return !!data;
}
export async function POST(req:Request){const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Authentication required'},{status:401});const body=await req.json();if(!body.communityId||!body.name)return NextResponse.json({error:'Community and role name required'},{status:400});if(!await authorized(supabase,body.communityId,user.id))return NextResponse.json({error:'Permission management access required'},{status:403});const {data:max}=await supabase.from('roles').select('rank_level').eq('community_id',body.communityId).order('rank_level',{ascending:false}).limit(1).maybeSingle();const {data:role,error}=await supabase.from('roles').insert({community_id:body.communityId,name:body.name,rank_level:Math.max(1,(max?.rank_level??100)-10),is_system:false,color:'#3b82f6',description:'Custom community role'}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({role});}
export async function PATCH(req:Request){const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Authentication required'},{status:401});const b=await req.json();if(!await authorized(supabase,b.communityId,user.id))return NextResponse.json({error:'Permission management access required'},{status:403});const r=b.role;const {error}=await supabase.from('roles').update({name:r.name,description:r.description,color:r.color,rank_level:r.rankLevel,discord_role_id:r.discordRoleId||null,organization_node_id:r.organizationNodeId||null,updated_at:new Date().toISOString()}).eq('id',r.id).eq('community_id',b.communityId);if(error)return NextResponse.json({error:error.message},{status:400});await supabase.from('role_permissions').delete().eq('role_id',r.id);if(b.permissions?.length){const {error:pe}=await supabase.from('role_permissions').insert(b.permissions.map((permission_key:string)=>({role_id:r.id,permission_key,allowed:true})));if(pe)return NextResponse.json({error:pe.message},{status:400});}return NextResponse.json({ok:true});}
