"use client";
import { ArrowDownLeft,ArrowUpRight,Banknote,BriefcaseBusiness,Building2,ChevronDown,ChevronUp,CircleDollarSign,Package,Plus,Send,Store,UserMinus,UserPlus,Users } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo,useState } from "react";
import styles from "./businesses.module.css";

type Tab="overview"|"banking"|"employees"|"payroll"|"inventory"|"store";
export default function BusinessesClient({character,businesses}:any){
 const router=useRouter(); const [selectedId,setSelectedId]=useState(businesses[0]?.id??""); const [tab,setTab]=useState<Tab>("overview"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(""); const [createOpen,setCreateOpen]=useState(businesses.length===0);
 const selected=useMemo(()=>businesses.find((b:any)=>b.id===selectedId)??businesses[0]??null,[businesses,selectedId]);
 async function request(url:string,payload:any){setBusy(payload.action||"request");setMessage("");const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();setBusy("");if(!r.ok){setMessage(b.error||"Action failed.");return false}router.refresh();return true}
 async function createBusiness(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await request("/api/economy/businesses",{characterId:character.id,name:f.get("name"),businessType:f.get("businessType"),description:f.get("description"),address:f.get("address"),phone:f.get("phone")});if(ok){setMessage("Business, operating account, storefront, and categories created.");setCreateOpen(false)}}
 async function hire(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await request("/api/businesses/employees",{businessId:selected.id,stateId:f.get("stateId"),roleName:f.get("roleName"),payType:f.get("payType"),payRate:f.get("payRate")})){setMessage("Employee hired.");e.currentTarget.reset()}}
 async function employeeAction(m:any,action:string){if(action==="pay"){const amount=prompt("Payment amount:");if(!amount)return;await request("/api/businesses/employees",{action,memberId:m.id,amount,description:prompt("Description:","Employee payment")||"Employee payment"});return}let roleName=null,payRate=null,reason=null;if(["promote","demote"].includes(action)){roleName=prompt("New role:",m.role_name);if(roleName===null)return;payRate=prompt("Pay rate:",String(m.pay_rate))}if(action==="fire"){reason=prompt("Reason:")||"";if(!confirm("Fire this employee?"))return}await request("/api/businesses/employees",{action,memberId:m.id,roleName,payRate,reason})}
 async function transfer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await request("/api/businesses/banking",{businessId:selected.id,toAccountNumber:f.get("toAccountNumber"),amount:f.get("amount"),description:f.get("description")})){setMessage("Business transfer completed.");e.currentTarget.reset()}}
 async function createPayroll(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await request("/api/payroll",{businessId:selected.id,payPeriodStart:f.get("payPeriodStart"),payPeriodEnd:f.get("payPeriodEnd")})}
 async function processPayroll(id:string){await request("/api/payroll",{action:"process",payrollRunId:id})}
 async function addCategory(){const name=prompt("New category name:");if(!name)return;await request("/api/businesses/store",{action:"category",businessId:selected.id,name,description:prompt("Category description:")||""})}
 async function publish(item:any){const price=prompt("Retail price:",String(Math.max(Number(item.average_cost||0),1)));if(!price)return;const categories=selected.store?.categories??[];const names=categories.map((c:any)=>c.name).join(", ");const chosen=prompt(`Category (${names}):`,categories[0]?.name||"General");const category=categories.find((c:any)=>c.name.toLowerCase()===String(chosen||"").toLowerCase())??categories[0];await request("/api/businesses/store",{inventoryId:item.id,categoryId:category?.id,price,description:prompt("Product description:",item.item_name)||item.item_name,active:true})}
 if(!selected&&!createOpen)return <div className={styles.page}><button className={styles.createBusinessButton} onClick={()=>setCreateOpen(true)}><Plus/>Register Business</button></div>;
 const account=selected?.bank_account;const employees=selected?.members??[];const tx=selected?.transactions??[];const payroll=selected?.payrollRuns??[];const inventory=selected?.inventory??[];const products=selected?.store?.products??[];
 return <div className={styles.page}>
  {message&&<div className={styles.message}>{message}</div>}
  <section className={styles.topActions}><button className={styles.createBusinessButton} onClick={()=>setCreateOpen(!createOpen)}><Plus/>Register Business</button>{businesses.length>0&&<label>Business<select value={selected?.id??""} onChange={e=>setSelectedId(e.target.value)}>{businesses.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}</section>
  {createOpen&&<form className={styles.createForm} onSubmit={createBusiness}><h3>Register a business</h3><p>This automatically creates its operating bank account, storefront, inventory, and default categories.</p><div><label>Name<input name="name" required/></label><label>Type<input name="businessType" required placeholder="Retail, automotive, restaurant..."/></label><label>Address<input name="address"/></label><label>Phone<input name="phone"/></label><label className={styles.full}>Description<textarea name="description"/></label></div><button disabled={!!busy}>Create Complete Business</button></form>}
  {selected&&<><section className={styles.businessHeader}><div className={styles.icon}><Building2/></div><div><span>{selected.business_type}</span><h2>{selected.name}</h2><code>{selected.business_number}</code></div><b>{selected.status}</b></section>
  <nav className={styles.tabs}>{(["overview","banking","employees","payroll","inventory","store"] as Tab[]).map(t=><button key={t} className={tab===t?styles.activeTab:""} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {tab==="overview"&&<section className={styles.stats}><article><Banknote/><span>Available balance</span><strong>${Number(account?.available_balance??0).toLocaleString()}</strong></article><article><Users/><span>Employees</span><strong>{employees.filter((e:any)=>e.status==="active").length}</strong></article><article><Package/><span>Inventory units</span><strong>{inventory.reduce((s:number,i:any)=>s+Number(i.quantity||0),0)}</strong></article><article><Store/><span>Store products</span><strong>{products.length}</strong></article></section>}
  {tab==="banking"&&<div className={styles.columns}><section className={styles.panel}><header><h3>Operating account</h3></header><dl className={styles.details}><div><dt>Account</dt><dd>{account?.account_number}</dd></div><div><dt>Balance</dt><dd>${Number(account?.balance??0).toLocaleString()}</dd></div></dl><form className={styles.compactForm} onSubmit={transfer}><input name="toAccountNumber" required placeholder="Receiving account"/><input name="amount" type="number" min=".01" step=".01" required/><input name="description" placeholder="Description"/><button><Send/>Transfer</button></form></section><section className={styles.panel}><header><h3>Transactions</h3></header><div className={styles.list}>{tx.map((t:any)=><article key={t.id}><div className={t.direction==="credit"?styles.credit:styles.debit}>{t.direction==="credit"?<ArrowDownLeft/>:<ArrowUpRight/>}</div><div><b>{t.description}</b><span>{t.transaction_type}</span></div><strong>{t.direction==="credit"?"+":"-"}${Number(t.amount).toLocaleString()}</strong></article>)}</div></section></div>}
  {tab==="employees"&&<section className={styles.panel}><form className={styles.hireForm} onSubmit={hire}><input name="stateId" required placeholder="State ID"/><input name="roleName" required placeholder="Role"/><select name="payType"><option value="hourly">Hourly</option><option value="salary">Salary</option><option value="commission">Commission</option></select><input name="payRate" type="number" min="0" required placeholder="Pay"/><button><UserPlus/>Hire</button></form><div className={styles.employeeGrid}>{employees.map((m:any)=>{const p=Array.isArray(m.character)?m.character[0]:m.character;const owner=m.character_id===selected.owner_character_id;return <article key={m.id}><h3>{p?.first_name} {p?.last_name}</h3><code>{p?.state_id}</code><p>{m.role_name} · Level {m.role_level} · ${Number(m.pay_rate).toLocaleString()}</p>{!owner&&<div><button onClick={()=>employeeAction(m,"promote")}><ChevronUp/>Promote</button><button onClick={()=>employeeAction(m,"demote")}><ChevronDown/>Demote</button><button onClick={()=>employeeAction(m,"pay")}><CircleDollarSign/>Pay</button><button onClick={()=>employeeAction(m,m.status==="active"?"fire":"rehire")}>{m.status==="active"?<UserMinus/>:<UserPlus/>}{m.status==="active"?"Fire":"Rehire"}</button></div>}</article>})}</div></section>}
  {tab==="payroll"&&<section className={styles.panel}><form className={styles.compactForm} onSubmit={createPayroll}><input name="payPeriodStart" type="date" required/><input name="payPeriodEnd" type="date" required/><button><Plus/>Create payroll</button></form><div className={styles.list}>{payroll.map((r:any)=><article key={r.id}><div><b>{r.payroll_number}</b><span>{r.pay_period_start} – {r.pay_period_end}</span></div><strong>${Number(r.net_amount).toLocaleString()} · {r.status}</strong>{r.status==="draft"&&<button onClick={()=>processPayroll(r.id)}>Process</button>}</article>)}</div></section>}
  {tab==="inventory"&&<section className={styles.panel}><header><h3>Business inventory</h3><p>Buy products from Stores using this business account. They will appear here.</p></header><div className={styles.inventoryGrid}>{inventory.length?inventory.map((i:any)=><article key={i.id}><Package/><div><h3>{i.item_name}</h3><span>{i.quantity-i.reserved_quantity} available · Cost ${Number(i.average_cost).toLocaleString()}</span></div><button onClick={()=>publish(i)}>Add to Store</button></article>):<p className={styles.emptyText}>No business inventory yet. Go to Stores and select “Buy for business.”</p>}</div></section>}
  {tab==="store"&&<section className={styles.panel}><header className={styles.storePanelHeader}><div><h3>{selected.store?.name||"Business Store"}</h3><p>Categories and products created from business inventory.</p></div><button onClick={addCategory}><Plus/>Add Category</button></header><div className={styles.categoryPills}>{(selected.store?.categories??[]).map((c:any)=><span key={c.id}>{c.name}</span>)}</div><div className={styles.inventoryGrid}>{products.length?products.map((p:any)=><article key={p.id}><Store/><div><h3>{p.name}</h3><span>{p.category} · ${Number(p.price).toLocaleString()} · Stock {p.stock_quantity}</span></div></article>):<p className={styles.emptyText}>No products published yet.</p>}</div></section>}</>}
 </div>
}
