import { AppShell } from "@/components/app-shell";
import { AlertTriangle, BadgeCheck, Bell, BookOpenCheck, ChevronRight, Clock3, FilePlus2, Gavel, Headphones, Search, ShieldAlert, Siren, UserRoundSearch } from "lucide-react";

const units = [
  ["2A-15", "PS5", "John Doe", "10-8", "Patrol"],
  ["3B-21", "Xbox X|S", "Jane Smith", "10-6", "Traffic Stop"],
  ["1C-12", "PS4", "Mike Brown", "10-7", "Station"],
  ["5K-09", "Xbox One", "Alex Johnson", "10-8", "Patrol"],
];

export default function LeoDashboard() {
  return <AppShell>
    <header className="topbar"><div><div className="breadcrumbs">Law Enforcement <ChevronRight size={14}/> LSPD <ChevronRight size={14}/> Patrol Division</div><h1>LSPD Dashboard</h1></div><div className="top-actions"><div className="global-search"><Search size={17}/><span>Search people, plates, IDs, reports...</span><kbd>⌘ K</kbd></div><button className="panic-button"><Siren size={18}/> PANIC</button><button className="icon-button"><Bell size={19}/></button><div className="profile-pill"><div className="avatar">JD</div><span><b>John Doe</b><small>2A-15 · PS5</small></span></div></div></header>
    <section className="page-content">
      <div className="welcome-row"><div><span className="eyebrow">LOS SANTOS POLICE DEPARTMENT</span><h2>Good afternoon, Officer Doe</h2><p>Patrol Division · Traffic Subdivision · PS5 Main</p></div><div className="shift-card"><span className="status-dot"/>ON DUTY <b>03:42:18</b><button>Clock Out</button></div></div>
      <div className="stats-grid five"><div className="stat-card"><Headphones/><span>Active Calls</span><strong>3</strong><small>1 priority call</small></div><div className="stat-card"><BadgeCheck/><span>Available Units</span><strong>12</strong><small>4 on PS5</small></div><div className="stat-card"><ShieldAlert/><span>Active BOLOs</span><strong>4</strong><small>2 vehicles</small></div><div className="stat-card"><Gavel/><span>Open Warrants</span><strong>7</strong><small>1 high risk</small></div><div className="stat-card"><Clock3/><span>Shift Reports</span><strong>6</strong><small>2 need review</small></div></div>
      <div className="content-grid main-dashboard">
        <section className="panel calls-panel"><div className="panel-title"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Active Calls</h2></div><button className="text-button">View all</button></div><div className="call-list"><article className="call critical"><div className="priority">PRIORITY 1</div><div><b>Officer Needs Assistance</b><span>Strawberry Ave / Davis Ave</span></div><div className="call-meta"><b>2 units</b><small>00:02:41</small></div></article><article className="call"><div className="priority blue">PRIORITY 2</div><div><b>Vehicle Pursuit</b><span>Great Ocean Highway</span></div><div className="call-meta"><b>3 units</b><small>00:08:17</small></div></article><article className="call"><div className="priority amber">PRIORITY 3</div><div><b>Suspicious Person</b><span>Vespucci Beach</span></div><div className="call-meta"><b>1 unit</b><small>00:15:29</small></div></article></div></section>
        <section className="panel units-panel"><div className="panel-title"><div><span className="eyebrow">CONNECTED PERSONNEL</span><h2>Unit Status</h2></div><select aria-label="Console filter"><option>All Consoles</option><option>PS4</option><option>PS5</option><option>Xbox One</option><option>Xbox Series X|S</option></select></div><div className="unit-table"><div className="table-row head"><span>Unit</span><span>Console</span><span>Officer</span><span>Status</span><span>Assignment</span></div>{units.map(([unit, consoleName, officer, status, assignment]) => <div className="table-row" key={unit}><b>{unit}</b><span className="platform-badge">{consoleName}</span><span>{officer}</span><span className="status-badge">{status}</span><span>{assignment}</span></div>)}</div></section>
        <section className="panel quick-panel"><div className="panel-title"><div><span className="eyebrow">TOOLS</span><h2>Quick Actions</h2></div></div><div className="quick-grid"><button><FilePlus2/>New Report</button><button><Gavel/>New Citation</button><button><UserRoundSearch/>Person Search</button><button><Search/>Plate Search</button><button><BookOpenCheck/>Penal Code Search</button><button className="supervisor"><BadgeCheck/>Self Dispatch<small>Supervisor</small></button><button className="backup"><AlertTriangle/>Request Backup</button><button className="panic-action"><Siren/>Activate Panic</button></div></section>
        <section className="panel alerts-panel"><div className="panel-title"><div><span className="eyebrow">ATTENTION</span><h2>Alerts & Notices</h2></div></div><div className="notice"><span className="notice-icon red"><Siren/></span><div><b>Panic system armed</b><p>Audio alerts broadcast to every connected on-duty unit.</p></div></div><div className="notice"><span className="notice-icon"><BookOpenCheck/></span><div><b>Penal code update</b><p>Traffic penalties updated by Command Staff.</p></div></div><div className="notice"><span className="notice-icon amber"><Clock3/></span><div><b>Report awaiting review</b><p>AR-26-00184 requires supervisor approval.</p></div></div></section>
      </div>
    </section>
  </AppShell>;
}
