"use client";
import { Building2,Car,Home,Package,RefreshCcw,Search,Shield,ShoppingCart,Store } from "lucide-react";
import { useMemo,useState } from "react";import { useRouter } from "next/navigation";import styles from "./stores.module.css";
export default function StoresClient({character,stores,accounts,businesses,canRestock}:any){
 const router=useRouter();const [storeType,setStoreType]=useState("all");const [storeId,setStoreId]=useState(stores[0]?.id??"");const [category,setCategory]=useState("all");const [search,setSearch]=useState("");const [destination,setDestination]=useState("personal");const [message,setMessage]=useState("");
 const visible=stores.filter((s:any)=>storeType==="all"||s.store_type===storeType);const selected=visible.find((s:any)=>s.id===storeId)||visible[0]||null;const products=selected?.products??[];const categories=Array.from(new Set(products.map((p:any)=>p.category||"Other"))).sort() as string[];const filtered=useMemo(()=>products.filter((p:any)=>(category==="all"||(p.category||"Other")===category)&&[p.name,p.sku,p.description,p.category].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase())),[products,category,search]);
 const isBusiness=destination.startsWith("business:");const businessId=isBusiness?destination.split(":")[1]:null;const business=businesses.find((b:any)=>b.id===businessId);const personalAccount=accounts[0];const rawBizAccount=business?.account;const bizAccount=Array.isArray(rawBizAccount)?rawBizAccount[0]:rawBizAccount;const selectedAccount=isBusiness?bizAccount:personalAccount;
 async function buy(p:any){if(!selectedAccount)return setMessage("No active account is available for this purchase.");const qty=p.product_type==="item"?Number(prompt("Quantity:","1")||0):1;if(!qty)return;const r=await fetch("/api/stores/purchase",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({characterId:character.id,accountId:selectedAccount.id,productId:p.id,quantity:qty,destinationType:isBusiness?"business":"personal",businessId})});const b=await r.json();if(!r.ok)return setMessage(b.error||"Purchase failed.");setMessage(isBusiness?`${p.name} added to ${business.name} inventory.`:`${p.name} added to personal inventory.`);router.refresh()}
 async function restock(p:any){const quantity=Number(prompt("Restock quantity:","25")||0);if(!quantity)return;const r=await fetch("/api/stores/restock",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:p.id,quantity,reason:prompt("Reason:","Founder restock")||"Founder restock"})});const b=await r.json();if(!r.ok)return setMessage(b.error||"Restock failed.");router.refresh()}
 const icon=(t:string)=>t==="vehicle"?<Car/>:t==="weapon"?<Shield/>:t==="property"?<Home/>:<Package/>;
 return <div className={styles.page}>{message&&<div className={styles.message}>{message}</div>}<section className={styles.hero}><div><span>Community stores</span><h2>{stores.length} storefronts</h2><p>Personal purchases go to personal inventory. Business purchases use the business account and go to business inventory.</p></div><Store/></section><section className={styles.filters}><label>Group<select value={storeType} onChange={e=>{setStoreType(e.target.value);setStoreId("");setCategory("all")}}><option value="all">All</option><option value="government">Government</option><option value="general">General</option><option value="business">Businesses</option></select></label><label>Store<select value={selected?.id??""} onChange={e=>{setStoreId(e.target.value);setCategory("all")}}>{visible.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Purchase for<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="personal">Personal inventory</option>{businesses.map((b:any)=><option key={b.id} value={`business:${b.id}`}>{b.name} inventory</option>)}</select></label><div className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/></div></section>{selected&&<section className={styles.storeHeader}><div>{selected.store_type==="business"?<Building2/>:<Store/>}</div><div><span>{selected.category_group} · {selected.store_type}</span><h2>{selected.name}</h2><p>{selected.description}</p></div><b>{filtered.length} products</b></section>}<section className={styles.grid}>{filtered.map((p:any)=><article key={p.id}><header><div className={styles.icon}>{icon(p.product_type)}</div><div><span>{p.category} · {p.product_type}</span><h3>{p.name}</h3><code>{p.sku}</code></div></header><p>{p.description}</p><dl><div><dt>Price</dt><dd>${Number(p.price).toLocaleString()}</dd></div><div><dt>Stock</dt><dd>{p.stock_quantity}</dd></div></dl><div className={styles.actions}><button disabled={p.stock_quantity<=0} onClick={()=>buy(p)}><ShoppingCart/>Buy for {isBusiness?business?.name:"Personal"}</button>{canRestock&&selected.restock_permission==="founder"&&<button onClick={()=>restock(p)}><RefreshCcw/>Restock</button>}</div></article>)}</section></div>
}
