"use client";
import { Archive, CheckCircle2, Eye, RotateCcw } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Character={id:string;state_id:string;first_name:string;middle_name:string|null;last_name:string;date_of_birth:string;gender:string|null;phone_number:string|null;address:string|null;occupation:string|null;status:string;is_archived:boolean;photo_url:string|null;created_at:string};
export default function CharacterCards({initialCharacters,initialActiveId}:{initialCharacters:Character[];initialActiveId:string|null}){
 const router=useRouter(); const [characters,setCharacters]=useState(initialCharacters); const [activeId,setActiveId]=useState(initialActiveId); const [message,setMessage]=useState("");
 async function activate(id:string){const r=await fetch('/api/characters/active',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({characterId:id})});const b=await r.json();if(!r.ok){setMessage(b.error);return;}setActiveId(id);setMessage('Active character updated.');router.refresh();}
 async function archive(id:string,value:boolean){const r=await fetch('/api/characters',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,is_archived:value})});const b=await r.json();if(!r.ok){setMessage(b.error);return;}setCharacters(v=>v.map(c=>c.id===id?{...c,is_archived:value}:c));if(value&&activeId===id)setActiveId(null);setMessage(value?'Character archived.':'Character restored.');router.refresh();}
 if(!characters.length)return <div className="empty-state character-empty"><b>No characters yet</b><span>Create your first civilian identity and receive an automatic State ID.</span><Link className="button primary" href="/civilian/characters/new">Create character</Link></div>;
 return <div>{message&&<div className="status-banner">{message}</div>}<div className="character-grid">{characters.map(c=><article key={c.id} className={`character-card${activeId===c.id?' active':''}${c.is_archived?' archived':''}`}><div className="character-avatar">{c.photo_url?<img src={c.photo_url} alt=""/>:<span>{c.first_name[0]}{c.last_name[0]}</span>}</div><div className="character-main"><div className="character-name"><h3>{c.first_name} {c.middle_name ? `${c.middle_name} `:''}{c.last_name}</h3>{activeId===c.id&&<span className="active-badge"><CheckCircle2 size={13}/>Active</span>}{c.is_archived&&<span className="archive-badge">Archived</span>}</div><code>{c.state_id}</code><p>{c.occupation||'No occupation'} · {c.status}</p><small>Born {new Date(`${c.date_of_birth}T00:00:00`).toLocaleDateString()}</small></div><div className="character-actions"><Link className="icon-button" href={`/civilian/characters/${c.id}`} title="View profile"><Eye size={16}/></Link>{!c.is_archived&&activeId!==c.id&&<button className="button compact" onClick={()=>activate(c.id)}>Use character</button>}<button className="icon-button" title={c.is_archived?'Restore':'Archive'} onClick={()=>archive(c.id,!c.is_archived)}>{c.is_archived?<RotateCcw size={16}/>:<Archive size={16}/>}</button></div></article>)}</div></div>;
}
