'use client';
import { BadgeCheck, CalendarDays, CheckCircle2, Clock3, FileText, Shield, XCircle } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

type Props={characterId:string;types:any[];applications:any[];licenses:any[]};
export default function LicenseApplicationPanel({characterId,types,applications,licenses}:Props){const router=useRouter();const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
 async function apply(typeId:string){setBusy(typeId);setMessage('');const r=await fetch('/api/licenses/applications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({characterId,licenseTypeId:typeId})});const b=await r.json();setBusy(null);if(!r.ok){setMessage(b.error||'Application failed.');return;}setMessage('Application submitted.');router.refresh();}
 const hasOpen=(typeId:string)=>applications.some(a=>a.license_type_id===typeId&&['submitted','testing','ready_for_review'].includes(a.status));const hasValid=(typeId:string)=>licenses.some(l=>l.license_type_id===typeId&&l.status==='valid');
 return <div className="dmv-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Available credentials</span><h2>Apply for a license</h2><p>Requirements are controlled by your community.</p></div></div>{message&&<div className="status-banner">{message}</div>}<div className="license-type-list">{types.map(t=><article key={t.id}><div className={`license-type-icon ${t.category}`}><Shield/></div><div className="license-type-copy"><div><b>{t.name}</b><code>{t.code}</code></div><p>{t.description}</p><div className="license-requirements"><span>{t.requires_written_test?'Written test':'No written test'}</span><span>{t.requires_practical_test?'Practical test':'No practical test'}</span><span>{t.validity_months} months</span><span>${Number(t.application_fee).toLocaleString()}</span></div></div><button className="button compact" disabled={busy===t.id||hasOpen(t.id)||hasValid(t.id)} onClick={()=>apply(t.id)}>{hasValid(t.id)?'Already issued':hasOpen(t.id)?'In progress':busy===t.id?'Submitting…':'Apply'}</button></article>)}</div></section>
 <div className="dmv-side-stack"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Issued credentials</span><h2>My licenses</h2></div></div><div className="issued-license-list">{licenses.length?licenses.map(l=><article key={l.id} className={`issued-license ${l.status}`}><div><BadgeCheck/><span>{Array.isArray(l.license_type)?l.license_type[0]?.name:l.license_type?.name}</span></div><code>{l.license_number}</code><dl><div><dt>Status</dt><dd>{l.status}</dd></div><div><dt>Issued</dt><dd>{new Date(l.issued_at).toLocaleDateString()}</dd></div><div><dt>Expires</dt><dd>{new Date(l.expires_at).toLocaleDateString()}</dd></div><div><dt>Points</dt><dd>{l.points}</dd></div></dl></article>):<div className="empty-state">No licenses have been issued.</div>}</div></section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Application history</span><h2>Tests and approvals</h2></div></div><div className="application-history">{applications.length?applications.map(a=><article key={a.id}><div className="application-line"><div><FileText/><span><b>{Array.isArray(a.license_type)?a.license_type[0]?.name:a.license_type?.name}</b><code>{a.application_number}</code></span></div><span className={`status-pill ${a.status}`}>{a.status.replaceAll('_',' ')}</span></div><div className="test-status-row"><span>{a.written_status==='passed'?<CheckCircle2/>:a.written_status==='failed'?<XCircle/>:<Clock3/>}Written: {a.written_status}</span><span>{a.practical_status==='passed'?<CheckCircle2/>:a.practical_status==='failed'?<XCircle/>:<Clock3/>}Practical: {a.practical_status}</span></div><small><CalendarDays/>Submitted {new Date(a.created_at).toLocaleString()}</small></article>):<div className="empty-state">No applications submitted.</div>}</div></section></div></div>;
}
